services:
  traefik:
    image: traefik:v3.5
    container_name: profile_traefik
    command:
      - "--api.dashboard=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
    networks:
      - web

  app:
    container_name: profile
    build:
      context: .
      dockerfile: ./docker/production.dockerfile
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL:?lost DATABASE_URL variable}
    expose:
      - "3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - local
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.profile.rule=Host(`${DOMAIN:?lost DOMAIN variable}`)"
      - "traefik.http.routers.profile.tls=true"
      - "traefik.http.routers.profile.tls.certresolver=letsencrypt"
      - "traefik.http.services.profile.loadbalancer.server.port=3000"
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: profile_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?lost POSTGRES_USER variable}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?lost POSTGRES_PASSWORD variable}
      POSTGRES_DB: ${POSTGRES_DB:?lost POSTGRES_DB variable}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local

networks:
  web:
    driver: bridge
  local:
    driver: bridge


volumes:
  postgres_data:
  letsencrypt: